### ISSUE TITLE
WebDAV Linux

### ISSUE THREAD

**Issue by sankarinfo** [seanox/devwex-test#1]
Hi Seanox

I am trying to build and deploy in linux environment, runtime cannot find annotations of controller, due to that cannot access excel, seems works fine in windows env, kindly advice

Thanks
Sankar

**Comment by seanox** [comment]
Let me try it in Docker.

**Comment by seanox** [comment]
Dockerfile:
```
FROM alpine:3.17 AS build-env
RUN apk add openjdk17 maven

WORKDIR /workspace/spring-webdav
COPY . /workspace/spring-webdav

EXPOSE 8080
CMD mvn -Dspring.profiles.active=demo \
    -Dexec.mainClass=com.seanox.api.Application \
    -Dexec.classpathScope=test exec:java \
    -Dhttps.proxyHost=proxy.local \
    -Dhttps.proxyPort=3128

# docker build -t spring-webdav:latest .
# docker run -p 8080:8080 spring-webdav:latest
# http://127.0.0.1:8080/
```
Everything worked for me.
If it does not work for you, please create a new problem here:
https://github.com/seanox/spring-webdav/issues
